"""add conversations and messages tables

Revision ID: ce01e24f2c79
Revises: 
Create Date: 2026-07-31 13:10:42.394490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce01e24f2c79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('participant_one_id', sa.Integer(), nullable=False),
    sa.Column('participant_twp_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_one_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['participant_twp_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('translated', sa.String(), nullable=False),
    sa.Column('source_lang', sa.String(), nullable=False),
    sa.Column('target_lang', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['Conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Messages')
    op.drop_table('Conversations')
    # ### end Alembic commands ###
